---
title: "lab13_warmup"
author: "Kellie Liu"
date: "2023-03-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(shiny)
library(shinydashboard)
```

```{r}
elephants <- readr::read_csv("data/ElephantsMF.csv") %>% clean_names()
```

```{r}
names(elephants)
```
```{r}
anyNA(elephants)
```
```{r}
glimpse(elephants)
```
```{r}
elephants %>% 
  ggplot(aes(x=age, y=height))+
  geom_point()+
  facet_wrap(~sex)
```

```{r, eval=F, echo=T}
ui <- fluidPage(
  titlePanel("Elephant Age vs. Height"),
    selectInput("sex", "Select Sex", choices = c("M", "F"),
              selected = "M"),
    helpText("Reference: Phyllis Lee, Stirling University, and are related to Lee, P., et al. (2013), enduring consequences of early experiences: 40-year effects of survival and success among African elephants (Loxodonta africana), Biology Letters, 9: 20130011."),
    plotOutput("plot", width = "500px", height = "400px")
)

server <- function(input, output, session) {
  session$onSessionEnded(stopApp)
  output$plot <- renderPlot({
      filter(elephants, sex==input$sex) %>% 
      ggplot(aes(x = age, y = height)) + 
      geom_point()
    })
}

shinyApp(ui, server)
``` 




